main: io.github.Infinight999.vouch4.vouch4
name: Vouch4
version: 2.0.1
author: Infinight999
description: Allows online players to vouch for new players
depend: [WorldGuard, Vault]
commands:
  vouch:
    description: command to vouch for a player
    usage: /<command> [player]
    aliases: [v]
    permission: Vouch4.vouch
  vouchedfor:
    description: command to check who has vouched for a player
    usage: /<command> [player]
    aliases: [vf]
    permission: Vouch4.vouchedfor